### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by johnsonphan95** [johnsonphan95/fletnix#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [ ] The `/login` page should not display a link to `Log In`. Same for `/signup`
- The signup page has a link to sign up.
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [ ] The site should look exactly like the actual site
- When I open the dev tools or resize the window, the background image gets messed up and does not cover the entire background
- Style your errors to look like Netflix's errors.
- [x] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

## Other
- [ ] Finding the sign up form was very confusing. I think if someone clicks sign up from the sign in page, the sign up form should just render.

**Comment by eshoule** [comment]
Looking good! Please fix the above unchecked items, and then you're good to go.
